# cgf cego6160@colorado.edu
# Loading, manipulation, and saving scripts for ensemble data ingested from NCAR FASTEDDY LES simulations
# 4.2.26

# ---------------- structures --------------
# memberinfo struct - attached to each member, read from the config script generated by pre_FErun_util/generate_ensemble.py
struct MemberInfo
    id          :: String            # 
    output_dir  :: String            # where does it keep the files?
    met_dir_deg :: Float64           # wind direction in degrees
    U_g_ms      :: Float64           # equivalent zonal wind speed
    V_g_ms      :: Float64           # equivalent meridional wind speed
    files       :: Vector{String}    # absolute paths, sorted numerically by timestep
    timesteps   :: Vector{Int}       # model-step suffix values (0, 3000, 6000, …)
    sim_times   :: Vector{Float32}   # simulation time in seconds per file
end

# EnsembleConfig struct - attached to an ensemble, describes each member with a memberinfo struct
struct EnsembleConfig
    n_members     :: Int                  # well named
    prior_members :: Vector{MemberInfo}   # 10 members that represent bayesian prior over the field
    truth_member  :: MemberInfo           # truth member, i.e. what we actually observe
end

# GridInfo struct, describes the LES terrain-following grid. Read from a single output file (u)
# Coordinate arrays are full 3D (terrain-following sigma coords)
struct GridInfo
    Nx        :: Int
    Ny        :: Int
    Nz        :: Int
    dx        :: Float32
    dy        :: Float32
    xPos      :: Array{Float32,3}    # (Nx, Ny, Nz)
    yPos      :: Array{Float32,3}
    zPos      :: Array{Float32,3}
    n_grid    :: Int                 # Nx * Ny * Nz
    state_dim :: Int                 # 3 * n_grid
end

# repacked wind field for a single member over time
struct NCfield
    t    :: Vector{Float32}      # (T,) timestamps in seconds
    grid :: GridInfo              # LES grid
    u    :: Array{Float32,4}     # (Nx, Ny, Nz, T) zonal wind, m/s
    v    :: Array{Float32,4}     # (Nx, Ny, Nz, T) meridional wind, m/s
    w    :: Array{Float32,4}     # (Nx, Ny, Nz, T) vertical wind, m/s
end


# ---------- output functions ----------------
# Unpack a single flat state vector [u;v;w] back into 3D fields.
function unpack_snapshot(x::AbstractVector{Float32}, grid::GridInfo)
    n = grid.n_grid
    u = reshape(x[1:n],    grid.Nx, grid.Ny, grid.Nz)
    v = reshape(x[n+1:2n], grid.Nx, grid.Ny, grid.Nz)
    w = reshape(x[2n+1:3n], grid.Nx, grid.Ny, grid.Nz)
    return u, v, w
end

# Reconstruct NCfield for member `member_idx` (1-based) from the full snapshot matrix.
# U is (state_dim, M*T) as built by build_snapshot_matrix; t_spinup must match what was used to build it.
# overloaded to get a single member (usually truth), or
function reconstruct_NCfield(U::Matrix{Float32}, member::MemberInfo,
                              grid::GridInfo;
                              t_spinup::Float64=900.0) :: NCfield
    mask  = _spinup_mask(member, t_spinup)
    T     = sum(mask)
    t_vec = member.sim_times[mask]
    u4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    v4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    w4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    for (i, col) in enumerate(1:T)
        u4[:,:,:,i], v4[:,:,:,i], w4[:,:,:,i] = unpack_snapshot(view(U, :, col), grid)
    end
    return NCfield(t_vec, grid, u4, v4, w4)
end
# with the whole U matrix, used to reconstruct arbitrary member for visualization or whatever. 
function reconstruct_NCfield(U::Matrix{Float32}, config::EnsembleConfig,
                              member_idx::Int, grid::GridInfo;
                              t_spinup::Float64=900.0) :: NCfield
    member = config.prior_members[member_idx]
    mask   = _spinup_mask(member, t_spinup)
    T      = sum(mask)
    t_vec  = member.sim_times[mask]

    # columns for this member in the snapshot matrix
    col_start = (member_idx - 1) * T + 1
    col_end   = member_idx * T

    u4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    v4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    w4 = Array{Float32,4}(undef, grid.Nx, grid.Ny, grid.Nz, T)
    for (i, col) in enumerate(col_start:col_end)
        u4[:,:,:,i], v4[:,:,:,i], w4[:,:,:,i] = unpack_snapshot(view(U, :, col), grid)
    end
    return NCfield(t_vec, grid, u4, v4, w4)
end


# ---------- input functions ------------------ 
# Read grid metadata once from any output file.
# NCDatasets.jl reverses netCDF dimension order: ds["u"][:,:,:,1] → (Nx, Ny, Nz).
# zPos is a full 3D array — terrain-following coordinates vary in all three dimensions.
function load_grid(filepath::String) :: GridInfo
    NCDataset(filepath, "r") do ds
        u    = ds["u"][:, :, :, 1]       # trigger read; shape (Nx, Ny, Nz)
        xPos = Float32.(ds["xPos"][:, :, :, 1])
        yPos = Float32.(ds["yPos"][:, :, :, 1])
        zPos = Float32.(ds["zPos"][:, :, :, 1])
        Nx, Ny, Nz = size(u)
        GridInfo(Nx, Ny, Nz, 20f0, 20f0, xPos, yPos, zPos, Nx*Ny*Nz, 3*Nx*Ny*Nz)
    end
end
# get ensemble config from file
function load_ensemble_config(config_path::String) :: EnsembleConfig
    @info "Parsing ensemble config: $config_path"
    cfg = JSON3.read(read(config_path, String))
    prior_members = [_make_member_info(m) for m in cfg.prior_members]
    truth_member  = _make_member_info(cfg.truth_member)
    return EnsembleConfig(length(prior_members), prior_members, truth_member)
end


# 
# Load a single snapshot as a flat state vector [u; v; w] (Float32).
# Flattening is Julia column-major: x varies fastest.
function load_snapshot(filepath::String) :: Vector{Float32}
    NCDataset(filepath, "r") do ds
        u = ds["u"][:, :, :, 1]    # (Nx, Ny, Nz)
        v = ds["v"][:, :, :, 1]
        w = ds["w"][:, :, :, 1]
        vcat(vec(u), vec(v), vec(w))
    end
end
# Load post-spinup snapshots for one member as a (state_dim, T) matrix.
function load_member_snapshots(member::MemberInfo;
                                t_spinup::Float64=900.0) :: Matrix{Float32}
    mask  = _spinup_mask(member, t_spinup)
    files = member.files[mask]
    T     = length(files)
    T == 0 && error("No post-spinup snapshots for member $(member.id) " *
                    "(t_spinup=$(t_spinup) s, max sim_time=$(maximum(member.sim_times)) s)")
    x0        = load_snapshot(files[1])
    state_dim = length(x0)
    U         = Matrix{Float32}(undef, state_dim, T)
    U[:, 1]   = x0
    for t in 2:T
        U[:, t] = load_snapshot(files[t])
    end
    return U
end


# ------data loading utilities helper functions --------------------
# Returns (sorted_paths, timesteps) for all output files in output_dir.
# Matches files named FE_Member<id>.<timestep>, sorts by numeric timestep.
function discover_member_files(output_dir::String, member_id::String)
    all_files = readdir(output_dir; join=false)
    pat = Regex("^FE_Member$(member_id)\\.([0-9]+)\$")
    matched = Tuple{Int,String}[]
    for f in all_files
        m = match(pat, f)
        if !isnothing(m)
            push!(matched, (parse(Int, m.captures[1]), joinpath(output_dir, f)))
        end
    end
    isempty(matched) && error("No output files found for member '$member_id' in $output_dir")
    sort!(matched, by=first)
    paths     = [p[2] for p in matched]
    timesteps = [p[1] for p in matched]
    return paths, timesteps
end

# _read_sim_times get vector of dump times available from NCAR fasteddy outputs
function _read_sim_times(files::Vector{String}) :: Vector{Float32}
    times = Vector{Float32}(undef, length(files))
    for (i, f) in enumerate(files)
        NCDataset(f, "r") do ds
            times[i] = Float32(ds["time"][1])
        end
    end
    return times
end

# parlay member info from file into struct
function _make_member_info(d) :: MemberInfo
    id         = String(d.id)
    output_dir = String(d.output_dir)
    files, timesteps = discover_member_files(output_dir, id)
    sim_times = _read_sim_times(files)
    return MemberInfo(
        id,
        output_dir,
        Float64(d.met_dir_deg),
        Float64(d.U_g_ms),
        Float64(d.V_g_ms),
        files,
        timesteps,
        sim_times,
    )
end

# Boolean mask: which files have sim_time >= t_spinup.
function _spinup_mask(member::MemberInfo, t_spinup::Float64) :: BitVector
    return member.sim_times .>= Float32(t_spinup)
end
